/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiStylistRouteImport } from './routes/ai-stylist'
import { Route as ClosetRouteImport } from './routes/closet'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StudioRouteImport } from './routes/studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStylistRoute = AiStylistRouteImport.update({
  id: '/ai-stylist',
  path: '/ai-stylist',
  getParentRoute: () => rootRouteImport,
} as any)
const ClosetRoute = ClosetRouteImport.update({
  id: '/closet',
  path: '/closet',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-stylist': typeof AiStylistRoute
  '/closet': typeof ClosetRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-stylist': typeof AiStylistRoute
  '/closet': typeof ClosetRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-stylist': typeof AiStylistRoute
  '/closet': typeof ClosetRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-stylist'
    | '/closet'
    | '/generate'
    | '/login'
    | '/profile'
    | '/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-stylist'
    | '/closet'
    | '/generate'
    | '/login'
    | '/profile'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/ai-stylist'
    | '/closet'
    | '/generate'
    | '/login'
    | '/profile'
    | '/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiStylistRoute: typeof AiStylistRoute
  ClosetRoute: typeof ClosetRoute
  GenerateRoute: typeof GenerateRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-stylist': {
      id: '/ai-stylist'
      path: '/ai-stylist'
      fullPath: '/ai-stylist'
      preLoaderRoute: typeof AiStylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/closet': {
      id: '/closet'
      path: '/closet'
      fullPath: '/closet'
      preLoaderRoute: typeof ClosetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiStylistRoute: AiStylistRoute,
  ClosetRoute: ClosetRoute,
  GenerateRoute: GenerateRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
